"""add vector and vector_text to tags

Revision ID: 2a836560736b
Revises: c54812e3fad3
Create Date: 2026-09-09 17:45:12.873773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a836560736b'
down_revision: Union[str, Sequence[str], None] = 'c54812e3fad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('vector_text', sa.Text(), nullable=True))
    op.add_column('tags', sa.Column('vector', sa.ARRAY(sa.REAL()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'vector')
    op.drop_column('tags', 'vector_text')
    # ### end Alembic commands ###
