"""empty message

Revision ID: eef2bb51b213
Revises: 4571de123acb
Create Date: 2026-09-03 19:43:07.480977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef2bb51b213'
down_revision: Union[str, Sequence[str], None] = '4571de123acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('time_validity', sa.String(length=20), server_default='daily-news', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'time_validity')
    # ### end Alembic commands ###
